export const environment = {
  production: true,
  urlRaiz: 'https://aribasas.sharepoint.com',
  urlWeb: 'https://aribasas.sharepoint.com/sites/Intranet/Servicios',
  urlWebGH: 'https://aribasas.sharepoint.com/sites/Intranet/Gestion-humana',
  urlWebJobs: 'https://enovelsoluciones.sharepoint.com/sites/IntranetAraujo/Jobs',
  urlReltativa: 'sites/Intranet/Servicios',
  listaOrdenes: 'OrdenServicios',
  listaConfiguracion: 'ConfiguracionOrdenServicio',
  listaUnegocios: 'UnidadNegocios',
  ListaEmpleados: 'Empleados',
  listaAprobadores: 'AprobadoresOrdenServicio',
  ListaServicios: 'Servicios',
  ListaEmpresas: 'EmpresasAraujoIbarra',
  ListaCeco: 'CentroCostos',
  ListaSedes: 'Sedes',
  ListaCecos: 'ParticipacionCecoOS',
  ListaProveedores: 'Proveedores',
  ListaCliente: 'Cliente',
  ListaOtroSi: 'OtroSiOrdenServicios'
};
