export const environment = {
  production: true,
  urlRaiz: 'https://aribasas.sharepoint.com',
  urlWeb: 'https://aribasas.sharepoint.com/sites/IntranetPruebas/servicios',
  urlWebGH: 'https://aribasas.sharepoint.com/sites/IntranetPruebas/gestion-humana',
  urlWebJobs: 'https://aribasas.sharepoint.com/sites/IntranetPruebas/Jobs',
  urlReltativa: 'sites/IntranetPruebas/servicios',
  listaOrdenes: 'OrdenServicios',
  listaConfiguracion: 'ConfiguracionOrdenServicio',
  listaUnegocios: 'UnidadNegocios',
  ListaEmpleados: 'Empleados',
  listaAprobadores: 'AprobadoresOrdenServicio',
  ListaServicios: 'Servicios',
  ListaEmpresas: 'EmpresasAraujoIbarra',
  ListaCeco: 'CentroCostos',
  ListaSedes: 'Sedes',
  ListaCecos: 'ParticipacionCecoOS',
  ListaProveedores: 'Proveedores',
  ListaCliente: 'Cliente',
  ListaOtroSi: 'OtroSiOrdenServicios'
};
